### ISSUE TITLE
Configure database

### ISSUE THREAD

**Issue by jepster** [javiereguiluz/easy-admin-demo#32]
If I run

> bin/console doctrine:database:create

I am getting

> Could not create database `asy-admin` for connection named default
> An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)

My parameters.yml file looks so:

> parameters:
>     database_url: easy-admin
>     secret: 23478qwjhsdf328z43sfsadf

How shall I define the database configuration?

**Comment by javiereguiluz** [comment]
If you use the `database_url` parameter, you must provide a database-compatible URL ... but you provided just the string `easy-admin`.

For example, to use SQLite and store the contents in the `var/data/easyadmin.sqlite` file inside your project, use this:

```
database_url: 'sqlite:///%kernel.root_dir%/../var/data/easyadmin.sqlite'
```

Otherwise, configure the database credentials separately: user, password, host, etc.

**Comment by jepster** [comment]
Thanks for the quick reply. This content in my parameters.yml file worked to configure my MySQL database connection:

```
parameters:
    database_url: mysql://root:password@localhost:8080/easy-admin
    secret: 23478qwjhsdf328z43sfsadf
```
